 editor/CMakeLists.txt                                                                                     |  76 [32m+++++++[m[31m---[m
 editor/daslang/AssetBrowser.das                                                                           |  14 [32m+[m[31m-[m
 editor/daslang/Editor.das                                                                                 |   2 [32m+[m[31m-[m
 editor/daslang/EntryPoint.das                                                                             |   2 [32m+[m[31m-[m
 editor/daslang/Mover.das                                                                                  |  44 [32m++++++[m
 editor/daslang/SceneViewPort.das                                                                          |   2 [32m+[m[31m-[m
 editor/imgui.ini                                                                                          |  46 [32m+++[m[31m---[m
 editor/include/editor/AppBootstrap.hpp                                                                    |  62 [31m--------[m
 editor/include/editor/AssetSourceDatabase.hpp                                                             |  47 [32m+++[m[31m----[m
 editor/include/editor/BaseSystem.hpp                                                                      |   8 [31m--[m
 editor/include/editor/BinaryParser.hpp                                                                    |  37 [32m+++++[m
 editor/include/editor/Components.hpp                                                                      |   6 [31m-[m
 editor/include/editor/ControllerManager.hpp                                                               |  32 [31m-----[m
 editor/include/editor/CreateFile.hpp                                                                      |  38 [32m+++++[m
 editor/include/editor/Editor.hpp                                                                          |  12 [32m+[m[31m-[m
 editor/include/editor/EditorApp.hpp                                                                       |   2 [31m-[m
 editor/include/editor/EditorArtifactLocator.hpp                                                           |  18 [32m+++[m
 editor/include/editor/EditorScriptSystem.hpp                                                              |  15 [31m--[m
 editor/include/editor/JsonParser.hpp                                                                      |  23 [32m++[m[31m-[m
 editor/include/editor/ReflectionSystem.hpp                                                                |  64 [31m---------[m
 editor/include/editor/SceneManagerController.hpp                                                          |  51 [31m-------[m
 editor/include/editor/SelectionManager.hpp                                                                |  54 [31m-------[m
 editor/include/editor/Spawner.hpp                                                                         |  20 [31m---[m
 editor/include/editor/TryEditorContext.hpp                                                                |  16 [32m+++[m
 editor/include/editor/asset_factories/AssetsFactoryManager.hpp                                            |  29 [32m++[m[31m--[m
 editor/include/editor/asset_factories/IAssetFactory.hpp                                                   |   6 [32m+[m[31m-[m
 editor/include/editor/asset_factories/MaterialAssetFactory.hpp                                            |  90 [32m++++++[m[31m------[m
 editor/include/editor/asset_factories/SceneAssetFactory.hpp                                               |  82 [31m-----------[m
 editor/include/editor/asset_factories/ShaderAssetFactory.hpp                                              |  48 [32m+++[m[31m----[m
 editor/include/editor/asset_inspector/MaterialAssetInspector.hpp                                          | 361 [32m+++++++++++++++++++++++[m[31m------------------------[m
 editor/include/editor/asset_inspector/ShaderAssetInspector.hpp                                            | 317 [32m++++++++++++++++++++[m[31m---------------------[m
 editor/include/editor/gui/AddressablesPanel.hpp                                                           | 150 [31m--------------------[m
 editor/include/editor/gui/BaseViewport.hpp                                                                |  44 [31m------[m
 editor/include/editor/gui/EditorGUI.hpp                                                                   |  34 [32m+[m[31m----[m
 editor/include/editor/gui/FileBrowserPanel.hpp                                                            |  47 [31m-------[m
 editor/include/editor/gui/GameViewportPanel.hpp                                                           |  81 [31m-----------[m
 editor/include/editor/gui/HierarchyPanel.hpp                                                              |  36 [31m-----[m
 editor/include/editor/gui/IPanel.hpp                                                                      |  24 [31m----[m
 editor/include/editor/gui/InspectorPanel.hpp                                                              |  44 [31m------[m
 editor/include/editor/gui/SceneViewportPanel.hpp                                                          | 132 [31m-----------------[m
 editor/include/editor/import/{GlslShaderImporter.hpp => GlslImporter.hpp}                                 |  14 [32m+[m[31m-[m
 editor/include/editor/import/GltfImporter.hpp                                                             |  84 [32m++++[m[31m-------[m
 editor/include/editor/import/IAssetImporter.hpp                                                           |   9 [32m+[m[31m-[m
 editor/include/editor/import/ImportSystem.hpp                                                             |  15 [32m+[m[31m-[m
 editor/include/editor/import/MeshProcessor.hpp                                                            |  53 [32m+++++++[m
 editor/include/editor/import/SlangImporter.hpp                                                            | 133 [32m++++++++++++++++++[m
 editor/include/editor/import/TextureProcessor.hpp                                                         |  53 [32m+++++++[m
 editor/include/editor/meta/ModelAssetMap.hpp                                                              |  15 [32m+[m[31m-[m
 editor/include/editor/utils/EditorGUIUtils.hpp                                                            | 106 [32m+++++++[m[31m-------[m
 editor/src/AssetSourceDatabase.cpp                                                                        | 246 [32m++++++++++++++++++++++++[m[31m--------[m
 editor/src/BaseSystem.cpp                                                                                 |  50 [31m-------[m
 editor/src/Editor.cpp                                                                                     | 151 [32m++++++++++[m[31m----------[m
 editor/src/EditorApp.cpp                                                                                  |  71 [32m+++++[m[31m-----[m
 editor/src/EditorGUI.cpp                                                                                  |  78 [32m++[m[31m---------[m
 editor/src/Module_Resources.cpp                                                                           |  86 [32m++++++++++++[m
 editor/src/Module_TryEditor.cpp                                                                           |  20 [32m+[m[31m--[m
 editor/src/Spawner.cpp                                                                                    | 266 [32m+++++++++++++++++++++++++++[m[31m--------[m
 editor/src/gui/FileBrowserPanel.cpp                                                                       | 690 [32m++++++++++++++++++++++++++++++++++++++++++++[m[31m---------------------------------------------[m
 editor/src/gui/HierarchyPanel.cpp                                                                         | 551 [32m+++++++++++++++++++++++++++++++++++[m[31m------------------------------------[m
 editor/src/gui/InspectorPanel.cpp                                                                         | 746 [32m++++++++++++++++++++++++++++++++++++++++++++++++[m[31m------------------------------------------------[m
 editor/src/gui/SceneViewportPanel.cpp                                                                     | 190 [32m++++++++++++[m[31m-------------[m
 editor/src/import/GltfImporter.cpp                                                                        | 958 [32m++++++++++++++++++++++++++++++++++++++++++++++++++++++[m[31m----------------------------------------------------------------------[m
 editor/src/import/MeshProcessor.cpp                                                                       | 280 [32m++++++++++++++++++++++++++++++++++++[m
 editor/src/import/StbImageTinyGLTFImpl.cpp                                                                |  11 [32m+[m[31m-[m
 editor/src/import/TextureImporter.cpp                                                                     |   6 [32m+[m[31m-[m
 editor/src/import/TextureProccessor.cpp                                                                   | 225 [32m+++++++++++++++++++++++++++++[m
 engine_content/artifacts/runtime/17044468730014679888/0                                                   | Bin [31m2000[m -> [32m2156[m bytes
 engine_content/artifacts/runtime/5555/0                                                                   |   1 [32m+[m
 engine_content/assets/s.shader                                                                            |   1 [32m+[m
 engine_content/assets/s.shader.meta                                                                       |   1 [32m+[m
 engine_content/assets/shaders/fragment.frag                                                               |   3 [32m+[m
 engine_content/assets/shaders/vertex.slang                                                                |  44 [32m++++++[m
 engine_content/assets/shaders/vertex.slang.meta                                                           |   1 [32m+[m
 engine_content/assets/shaders/vertex.vert                                                                 |  31 [31m----[m
 engine_content/assets/shaders/vertex.vert.meta                                                            |   1 [31m-[m
 engine_source/async/include/engine/async/Executor.hpp                                                     |  31 [32m++[m[31m--[m
 engine_source/async/include/engine/async/GlobalExecutors.hpp                                              |  24 [32m++[m[31m--[m
 engine_source/async/include/engine/async/MainThreadExecutor.hpp                                           |   4 [32m+[m[31m-[m
 engine_source/async/include/engine/async/PollHandle.hpp                                                   |  17 [32m++[m[31m-[m
 engine_source/async/include/engine/async/SyncWait.hpp                                                     |   9 [32m+[m[31m-[m
 engine_source/async/include/engine/async/Task.hpp                                                         |  71 [32m+++++++[m[31m---[m
 engine_source/async/include/engine/async/ThreadPoolExecutor.hpp                                           |  19 [32m+[m[31m--[m
 engine_source/async/include/engine/async/WhenAll.hpp                                                      |  15 [32m+[m[31m-[m
 engine_source/core/CMakeLists.txt                                                                         |   8 [32m+[m[31m-[m
 engine_source/core/include/engine/core/Assert.hpp                                                         |   9 [32m+[m[31m-[m
 engine_source/core/include/engine/core/BaseSystem.hpp                                                     |   8 [31m--[m
 engine_source/core/include/engine/core/ComponentRegistry.hpp                                              | 128 [31m-----------------[m
 engine_source/core/include/engine/core/Components.hpp                                                     |  65 [31m---------[m
 engine_source/core/include/engine/core/Engine.hpp                                                         |  48 [32m++[m[31m-----[m
 engine_source/core/include/engine/core/Error.hpp                                                          | 105 [32m++++++++++[m[31m----[m
 engine_source/core/include/engine/core/ErrorCode.hpp                                                      |   4 [32m+[m[31m-[m
 engine_source/core/include/engine/core/HlslppFormatter.hpp                                                | 274 [32m++++++++++++++++++++++++++++++++++++[m
 engine_source/core/include/engine/core/Inline.hpp                                                         |   5 [32m+[m
 engine_source/core/include/engine/core/InputState.hpp                                                     |  14 [32m+[m[31m-[m
 engine_source/core/include/engine/core/Log.hpp                                                            | 161 [32m++++++++++++++[m[31m-------[m
 engine_source/core/include/engine/core/MakeError.hpp                                                      |  29 [32m++++[m
 engine_source/core/include/engine/core/Random.hpp                                                         |  55 [32m++++++++[m
 engine_source/core/include/engine/core/RandomUtil.hpp                                                     |  15 [31m--[m
 engine_source/core/include/engine/core/{Expected.hpp => Result.hpp}                                       |   0
 engine_source/core/include/engine/core/Scene.hpp                                                          |  42 [31m------[m
 engine_source/core/include/engine/core/SceneManager.hpp                                                   |  40 [31m------[m
 engine_source/core/include/engine/core/ScriptSystem.hpp                                                   |  98 [32m++++++[m[31m-------[m
 engine_source/core/include/engine/core/SlotMap.hpp                                                        | 132 [32m+++++++++++++++++[m
 engine_source/core/include/engine/core/Time.hpp                                                           |  10 [32m+[m[31m-[m
 engine_source/core/include/engine/core/TypeRegistry.hpp                                                   |  20 [32m+++[m
 engine_source/core/src/BaseSystem.cpp                                                                     |  49 [31m-------[m
 engine_source/core/src/Log.cpp                                                                            |  11 [32m+[m[31m-[m
 engine_source/core/src/SceneManager.cpp                                                                   |  37 [31m-----[m
 engine_source/core/src/ScriptSystem.cpp                                                                   | 120 [32m++++++++[m[31m--------[m
 engine_source/core/src/Time.cpp                                                                           |   3 [32m+[m[31m-[m
 engine_source/daslang/Input.das                                                                           |  44 [32m++++++[m
 engine_source/daslang/Render.das                                                                          |  95 [32m++++++++++++[m[31m-[m
 engine_source/daslang/Temp.das                                                                            |   7 [31m-[m
 engine_source/daslang/Types.das                                                                           |  44 [32m+++[m[31m---[m
 engine_source/graphics/CMakeLists.txt                                                                     |  13 [32m+[m[31m-[m
 engine_source/graphics/include/engine/graphics/AssetTypes.hpp                                             |  42 [32m++++++[m
 engine_source/graphics/include/engine/graphics/May.hpp                                                    |   9 [31m--[m
 engine_source/graphics/include/engine/graphics/PipelineDescriptor.hpp                                     |   7 [32m+[m[31m-[m
 engine_source/graphics/include/engine/graphics/PipelineManager.hpp                                        | 149 [32m++++++++++++++[m[31m------[m
 engine_source/graphics/include/engine/graphics/RenderAdapter.hpp                                          |  23 [32m+++[m
 engine_source/graphics/include/engine/graphics/RenderCommon.hpp                                           |  45 [32m+++[m[31m---[m
 engine_source/graphics/include/engine/graphics/RenderProfile.hpp                                          |   2 [31m-[m
 engine_source/graphics/include/engine/graphics/RenderSystem.hpp                                           |  25 [32m++[m[31m--[m
 engine_source/graphics/include/engine/graphics/RuntimeTypes.hpp                                           | 154 [32m++++++++++++++++++++[m
 engine_source/graphics/include/engine/graphics/Transform.hpp                                              |  18 [32m+++[m
 engine_source/graphics/include/engine/graphics/Types.hpp                                                  | 200 [31m--------------------------[m
 engine_source/graphics/include/engine/graphics/loaders/JsonLoader.hpp                                     |  27 [32m++++[m
 engine_source/graphics/include/engine/graphics/loaders/MaterialLoader.hpp                                 | 116 [32m++++++++[m[31m-------[m
 engine_source/graphics/include/engine/graphics/loaders/MeshLoader.hpp                                     |  83 [32m+++++[m[31m------[m
 engine_source/graphics/include/engine/graphics/loaders/ShaderAssetLoader.hpp                              | 101 [31m-------------[m
 engine_source/graphics/include/engine/graphics/loaders/ShaderLoader.hpp                                   | 116 [32m+++++++++++++++[m
 engine_source/graphics/include/engine/graphics/loaders/TextureLoader.hpp                                  | 174 [32m++++++++++++++[m[31m---------[m
 engine_source/graphics/src/GraphicsContext.cpp                                                            |   2 [32m+[m[31m-[m
 engine_source/graphics/src/May.cpp                                                                        |  56 [31m--------[m
 engine_source/graphics/src/Module_Renderer.cpp                                                            | 195 [32m+++++++++++++++++[m[31m---------[m
 engine_source/graphics/src/RenderAdapter.cpp                                                              | 115 [32m+++++++++++++++[m
 engine_source/graphics/src/RenderSystem.cpp                                                               |  63 [32m+++++[m[31m----[m
 engine_source/resources/CMakeLists.txt                                                                    |  10 [32m+[m[31m-[m
 engine_source/resources/include/engine/resources/AssetDatabase.hpp                                        |  37 [31m-----[m
 engine_source/resources/include/engine/resources/AssetRegistry.hpp                                        |  32 [32m+++++[m
 engine_source/resources/include/engine/resources/AssetTypes.hpp                                           |  17 [32m+[m[31m--[m
 engine_source/resources/include/engine/resources/AsyncFileManager.hpp                                     |  76 [32m++++++[m[31m----[m
 engine_source/resources/include/engine/resources/Content.hpp                                              |   3 [32m+[m[31m-[m
 engine_source/resources/include/engine/resources/EastlGlazeSerializers.hpp                                |  95 [32m+++++++++++++[m
 engine_source/resources/include/engine/resources/GLMSerialization.hpp                                     | 116 [32m+++++++[m[31m--------[m
 engine_source/resources/include/engine/resources/ICacheBase.hpp                                           |  48 [31m-------[m
 engine_source/resources/include/engine/resources/MaterialAssetData.hpp                                    |  17 [31m---[m
 engine_source/resources/include/engine/resources/MeshBinary.hpp                                           |  75 [32m++++++++++[m
 engine_source/resources/include/engine/resources/MeshDataLoader.hpp                                       |  55 [31m--------[m
 engine_source/resources/include/engine/resources/ReadFullFile.hpp                                         |   4 [32m+[m[31m-[m
 engine_source/resources/include/engine/resources/ResourceCache.hpp                                        | 192 [32m+++++++++++++++++++++++++[m
 engine_source/resources/include/engine/resources/ResourceControlBlock.hpp                                 |  22 [32m+++[m
 engine_source/{graphics/include/engine/graphics => resources/include/engine/resources}/ResourceHandle.hpp |  67 [32m+++[m[31m------[m
 engine_source/resources/include/engine/resources/ResourceManager.hpp                                      | 110 [32m++++++++++++[m[31m---[m
 engine_source/resources/include/engine/resources/TextureBinary.hpp                                        |  84 [32m+++++++++++[m
 engine_source/resources/include/engine/resources/TextureTypes.hpp                                         | 180 [32m++++++++++++++++++++++++[m
 engine_source/resources/include/engine/resources/Types.hpp                                                |  37 [31m-----[m
 engine_source/resources/include/engine/resources/Vertex.hpp                                               |  69 [32m+++++++++[m
 engine_source/resources/src/MeshBinary.cpp                                                                |  78 [32m+++++++++++[m
 engine_source/resources/src/TextureBinary.cpp                                                             | 154 [32m++++++++++++++++++++[m
 game/assets/lance.glb.meta                                                                                |   1 [32m+[m
 game/assets/lock_paving_square_2k.glb                                                                     | Bin [31m3471456[m -> [32m0[m bytes
 game/assets/scenes/nameless_scene_1.scene                                                                 | 448 [31m----------------------------------------------------------[m
 game/assets/scripts/main.das                                                                              | 206 [32m++++++++[m[31m-------------------[m
 game/assets/tinylivingpack.glb                                                                            | Bin [31m0[m -> [32m5968840[m bytes
 game/assets/tinylivingpack.glb.meta                                                                       |   1 [32m+[m
 modules/tryeditor/tryeditor.shared_module                                                                 | Bin [31m3472632[m -> [32m3495440[m bytes
 modules/tryengine/.das_module                                                                             |   2 [32m+[m
 modules/tryengine/tryengine.shared_module                                                                 | Bin [31m965248[m -> [32m311200[m bytes
 169 files changed, 7125 insertions(+), 6122 deletions(-)
